Xcorner 18 contact us
xfiveco/xcorner pull request #99
Opened 2024-01-15 14:44 UTC by mgbelegu

#### Changes:

- Styling of the contact page in BigCommerce

2024-02-05 16:01 UTC, marcinkrzeminski requested changes

2024-02-05 16:01 UTC, marcinkrzeminski commented on assets/scss/pages/contact-page.scss
> +.c-contact-page__section {
@mgbelegu please use `p-` prefix for pages.

2024-02-05 16:01 UTC, marcinkrzeminski commented on assets/scss/pages/contact-page.scss
> +}
@mgbelegu can't we use the `c-common__title` here from the other pull request?

2024-02-05 16:01 UTC, marcinkrzeminski commented on assets/scss/pages/contact-page.scss
> +}
@mgbelegu move this to a separate component.

2024-02-05 16:01 UTC, marcinkrzeminski commented on assets/scss/pages/contact-page.scss
> +    }
@mgbelegu remove this one please, since it's going to be handled by the `c-wysiwyg` component.

2024-02-06 08:32 UTC, closed without merging

2024-02-06 08:38 UTC, mgbelegu commented
@marcinkrzeminski After rebase most things have been fixed. Can you take another look please?